### ISSUE TITLE
500 errors

### ISSUE THREAD

**Issue by rayslinky** [ipstatic/wallop-docker#2]
I just tried your image out and am having the same issue as:
https://github.com/maddox/wallop/issues/64

192.168.1.33 - - [31/Jul/2019:22:02:53 +0000] "GET /channels HTTP/1.1" 500 30 0.0020
2019-07-31 22:02:55 - NoMethodError - undefined method `[]' for nil:NilClass:
        /wallop/lib/wallop.rb:128:in `block in lineup'
        /wallop/lib/wallop.rb:126:in `each'
        /wallop/lib/wallop.rb:126:in `lineup'
        app/app.rb:47:in `block in <class:App>'

any thoughts?

**Comment by rayslinky** [comment]
Nevermind, it works fine with host network mode
